# Generated by Django 4.2.7 on 2024-07-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_booking_guest_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Awaiting confirmation', 'Awaiting Confirmation'), ('Booking Confirmed', 'Booking Confirmed'), ('Booking Rejected', 'Booking Rejected'), ('Booking Expired', 'Booking Expired')], default='Awaiting confirmation', max_length=25),
        ),
    ]
