# Generated by Django 4.2.7 on 2024-07-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200, unique=True)),
                ('price', models.FloatField()),
                ('drink_type', models.IntegerField(choices=[(0, 'Wines'), (1, 'Beers'), (2, 'Cocktails')], default=0)),
                ('available', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-drink_type'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200, unique=True)),
                ('price', models.FloatField()),
                ('food_type', models.IntegerField(choices=[(0, 'Starters'), (1, 'Mains'), (2, 'Desserts')], default=0)),
                ('available', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-food_type'],
            },
        ),
    ]
